### ISSUE TITLE
Cannot add zone element!

### ISSUE THREAD

**Issue by imwihfm** [mei-friend/mei-friend#103]
As I try to add a new zone to the facsimile I get the following error:

> Cannot add zone element. Please select an allowed element first (abbr,accid,add,anchoredText,annot,arpeg,artic,barLine,beam,beamSpan,beatRpt,bracketSpan,breath,caesura,chord,clef,custos,damage,del,dir,dot,dynam,ending,expan,f,fTrem,fb,fermata,fig,fing,gliss,graceGrp,graphic,grpSym,hairpin,halfmRpt,harm,keyAccid,keySig,label,labelAbbr,layer,lb,ligature,lv,mNum,mRest,mRpt,mRpt2,mSpace,mdiv,measure,mensur,meterSig,meterSigGrp,mordent,multiRest,multiRpt,nc,neume,note,num,octave,orig,pb,pedal,pgFoot,pgHead,phrase,plica,proport,reh,rest,restore,sb,section,sic,slur,space,staff,staffGrp,stem,supplied,syl,syllable,symbol,tempo,tie,trill,tuplet,turn,unclear,verse).

This happens despite having selected some element (eg. a note, measure etc) in the verovio-window.
What can be the cause of this problem?

A second problem associated with facsimile that I am encountering: Clicking the "Add facsimile" option adds an empty facsimile element like `<facsimile xml:id="f6222yg1"/>` no surfaces, no `<pb>` element etc.

**Comment by wergo** [comment]
Thanks for raising this issue. 

Ad 1): It is hard to speculate, why this happens in your situation. mei-friend currently inserts the zone element referenced from the currently selected element in the editor. If you use the drag-select way for selecting elements, it will still try to reference from the currently selected element. While you drag with mouse-down, mei-friend keeps selecting in the encoding the latest element under your mouse pointer. To solve your problem, click select just one (allowed) element in the notation, or select the element by clicking in the encoding. 

If you think that another behavior would be more useful, please let us know.

Ad 2): Please see https://mei-friend.github.io/docs/advanced/facsimile/ `"Add facsimile"` adds an empty facsimile element. In case there are `pb` elements in the encoding, it will add surface and graphic elements. It does not add any `pb` elements.
