### ISSUE TITLE
Johann Melchhior Molter: Concertino for two flutes (https://s9.imslp.org/files/imglnks/usimg/7/73/IMSLP110578-PMLP224356-Concertino_-_Mus_Hs_362.pdf)

### ISSUE THREAD

**Issue by AndreasK4** [mei-friend/mei-friend#104]
# Propose an addition to the public repertoire
mei-friend provides access to publicly-licensed encodings through the 'Public repertoire' and 'Open URL' options of the File menu, and through the 'Fork repository' option of the GitHub menu. We welcome proposed additions to the list of available encodings using the proposal form below. 

## Requirements
* Supported encoding format: MEI, Kern, MusicXML (raw and compressed), ABC, PAE.
* Encoding must be available via public Github repositories.
* Encoding must be made available under a public (e.g., a Creative Commons) license. 
* The licensing of the encoding must be explicitly stated in the GitHub repository and/or in the encoding itself, e.g. using the MEI [useRestrict](https://music-encoding.org/guidelines/v4/elements/userestrict) element.

### Title of the composition 
E.g., Piano Sonata Op. 27 No. 1, "Sonata quasi una fantasia"

### Composer name
E.g., Ludwig van Beethoven

### GitHub user/organization and repository name 
E.g., trompamusic-encodings/Beethoven_Op27_No1_HenleUrtext

### Raw Github URL of the encoding 
E.g., https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op27_No1_HenleUrtext/main/Beethoven_Op27_No1_2_HenleUrtext.mei

### License 
E.g., CC-BY-4.0

**Comment by wergo** [comment]
Thank you for your suggestion. Would you be willing to contribute an MEI encoding?
