### ISSUE TITLE
Loading a new document does not reset undo history

### ISSUE THREAD

**Issue by maxrothman** [mei-friend/mei-friend#117]
**Describe the bug**
Undo history is kept when a new document is loaded, such that if you undo immediately after loading a document you replace the entire contents of the editor with the contents of the previous document

**To Reproduce**
1. Load a document (A)
2. Load a different document (B)
3. Undo

The contents of the editor will be replaced with those of doc A

**Expected behavior**
Undo history is cleared when a document is loaded

**Notes**
This should be pretty straightforward to fix, `doc.clearHistory()` just needs to be called when a document is loaded. I'm happy to look into making a PR for this.

**Comment by wergo** [comment]
Thanks for spotting this. Could you make a PR to develop?

**Comment by maxrothman** [comment]
I took a look into the places where this call could be added. My instinct was that the best place to add it would be in a single central function that handles file loading so that it always gets called whenever a file is loaded. Unfortunately there doesn't seem to be a clear candidate for such a function. Here are the candidates I found by looking through the imports of `github-menu.js`:
- handleEncoding: seems pretty focused, therefore not a great option
- set(meiFileInfo | FileChangedState | FileLocationType): none of these seem like great options since they're purely setters. Of them, I guess `setMeiFileInfo` is the least bad?
- updateFileStatusDesplay: I guess the best option of the bunch? Also pretty focused, but called in all the right places I think?

Or is there another approach for where to add the call to `doc.clearHistory()`? I could use a little guidance on this since I'm not super familiar with mei-friend's code.

**Comment by wergo** [comment]
Thanks so much for raising this @maxrothman and proposing the easy solution (added to `main::loadDataInEditor()`). Fixed through b45874868db3e1de1e68475cda87cbf1ae1d3a5c and pushed to https://testing.mei-friend.mdw.ac.at. Will be added to the next release in the coming weeks.
