### ISSUE TITLE
Adding supplied for @artic and @accid

### ISSUE THREAD

**Issue by wergo** [mei-friend/mei-friend#14]
(Raised by @o-sapov)
Currently, supplied elements may only be added around selected elements (using shortcut `U`). 

Feature request: 

1. Insert – Supplied artic (CTRL + U) on selected `note`/`chord`: makes element out of `@artic` attribute (if existing) and surrounds it with a `supplied` element.
2. Insert – Supplied accid (CTRL + SHIFT + U) on selected `note`: makes element out of `@accid` attribute (if existing) and surrounds it with a `supplied`element.

**Comment by wergo** [comment]
Solved as above. 

(Suggested by @o-sapov: Additionally, if the `xml:ids` follow the schema by the Mozarteum DIME (`'note_1234'`), both the `supplied` element and the converted attribute element (`artic` or `accid`) will have an `xml:id` with the identical underscore/number after the node name (such as `'supplied_1234'` and `'artic_1234'`).

**Comment by o-sapov** [comment]
Thank you very much for implementing of this very important functionality!
Special thanks for the` @xml:id`-part :) 

I tested the function and noted that the combination with chord does not work as expected. For instance, applying `ctrl+u` on this code (focus on any note element):

<details>
<summary>&lt;chord&gt;[@artic]</summary>
<p>

```xml
<chord artic="stacc" dur="4" tstamp="1" xml:id="chord_2970">
  <note oct="5" pname="d" xml:id="note_2976"/>
  <note oct="4" pname="a" xml:id="note_2982"/>
  <note accid.ges="s" oct="4" pname="f" xml:id="note_2988"/>
</chord>
```
</p>
</details>  

or this: 
<details>
<summary>&lt;chord&gt;/&lt;artic&gt;</summary>
<p>

```xml
<chord dur="4" tstamp="1" xml:id="chord_2970">
  <note oct="5" pname="d" xml:id="note_2976"/>
  <note oct="4" pname="a" xml:id="note_2982"/>
  <note accid.ges="s" oct="4" pname="f" xml:id="note_2988"/>
  <artic artic="stacc" xml:id="artic_2970"/>
</chord>
```
</p>
</details>  

Should produce this:

<details>
<summary>output</summary>
<p>

```xml
<chord dur="4" tstamp="1" xml:id="chord_2970">
  <note oct="5" pname="d" xml:id="note_2976"/>
  <note oct="4" pname="a" xml:id="note_2982"/>
  <note accid.ges="s" oct="4" pname="f" xml:id="note_2988"/>
  <supplied xml:id="supplied_2970">
    <artic artic="stacc" xml:id="artic_2970"/>
  </supplied>
</chord>
```
</p>
</details>  


But currently, I'm getting this warning:

<img width="900" alt="nma_k310-001_m68" src="https://user-images.githubusercontent.com/24490898/220162909-4c5f39e8-fb0f-464d-9416-47422f11608f.png">

([mei-friend staging-0.8.3](https://github.com/mei-friend/mei-friend) (19 Feb 2023).  [Verovio 3.14.0-134f277](https://github.com/rism-digital/verovio/releases/tag/version-3.14.0))

I also tried to focus on `<chord>` element in the code panel, which has no effect. Anyway, the functionality is most convinient if the focus is on the note symbol in the rendering panel.


Maybe the respective code from the atom package version of mei-friend might be helpful:

<details>
<summary> supplyAttribute()</summary>
<p>

```javascript
  /**
  * Looks up if the requested attribute already exists as an element, if not, it will be converted.
  * Then this element will wrapped into a <supplied> tag 
  * If parent of the element is a <chord>, then the attribute of the <chord> will be processed same way
  * @author Oleksii Sapov <sapov@mozarteum.at>
  * @param {object} txtEdr - among others contains MEI
  * @param {string} attrName - the name of the atttribute to be supplied
  * @return {void} Nothing
  */
  supplyAttribute(txtEdr, attrName) {
    this.loadXml(txtEdr);
    let ids = speed.filterElements(this.selectedElements, this.xmlDoc);
    console.log("Run supplyAttribute(" + attrName + ") on " + ids)
    this.updateNotation = false;
    let i, range;
    for (i = 0; i < ids.length; i++) {
      let id = ids[i];
      var el = this.xmlDoc.querySelector("[*|id='" + id + "']");
      if (!(el)) { console.log("No element " + id + "!"); continue; }

      // supply artic for chords
      let elParent = el.parentElement;
      if (elParent.tagName == 'chord' && attrName == 'artic') {
        console.log("The element " + id + " is child of a chord. Therefore the chord attribute " + attrName + "will be supplied!");
        el = elParent;
      }

      // Some attributes can also exist es elements. For instance, @accid and <accid>
      let attributeAsDescendant = el.getElementsByTagName(attrName)[0];

      if (attributeAsDescendant) {
        // If the attribute exists
        if (!(attributeAsDescendant.hasAttribute(attrName))) { console.log("No attribute " + attrName + "!"); continue; }
        // If the element is already supplied
        if (attributeAsDescendant.parentNode.tagName == 'supplied') { console.log("The element '" + attributeAsDescendant.getAttribute('xml:id') + "' is already supplied!"); continue; }
        // otherwise wrap a supply tag around it
        this.wrapSupply(attributeAsDescendant);
      } else {
        // If the attribute exists
        if (!(el.hasAttribute(attrName))) { console.log("No attribute " + attrName + "!"); continue; }
        newEl_id = this.attr2el(el, attrName);
        this.wrapSupply(el.querySelector("[*|id='" + newEl_id + "']"));
      }
      let uuid;
      uuid ? ids[i] = uuid : ids[i] = id;
      range = speed.replaceInTextEditor(txtEdr, el, true);
      txtEdr.autoIndentSelectedRows();
    }
    if (range) txtEdr.setCursorBufferPosition(range.end);
    this.selectedElements = ids;
    this.speedMode ? this.updateLayout(txtEdr) : this.updateData(txtEdr);
    this.setFocusToVerovioPane();
  }


  /**
  * Converts an attribute into a child element.
  * A helper function. Used for supplyAttribute()
  * @author Oleksii Sapov <sapov@mozarteum.at>
  * @param {object} el - MEI element
  * @param {string} attrName - the name of the atttribute to be converted
  * @return {string} @xml:id of the new element
  */
  attr2el(el, attrName) {
    let newEl = document.createElementNS(speed.meiNameSpace, attrName);
    let newEl_id = this.createNewId(el, attrName);
    newEl.setAttributeNS(speed.xmlNameSpace, 'xml:id', newEl_id);
    let suppliedAttrValue = el.attributes[attrName].value;
    newEl.setAttribute(attrName, suppliedAttrValue);
    el.appendChild(newEl);
    el.removeAttribute(attrName);
    return newEl_id;
  }


  /**
  *Wraps an element into a <supply> tag
  * A helper function. Used for supplyAttribute() and supplyElement()
  * @author Oleksii Sapov <sapov@mozarteum.at>
  * @param {object} el - MEI element 
  * @return {object} <supplied> tag containing the original element
  */
  wrapSupply(el) {
    let parent = el.parentNode;
    let sup = document.createElementNS(speed.meiNameSpace, 'supplied');
    let id = this.createNewId(el, 'supplied');
    sup.setAttributeNS(speed.xmlNameSpace, 'xml:id', id);
    parent.replaceChild(sup, el);
    sup.appendChild(el);
    return parent;
  }

```
</p>
</details>  

It produces the needed result:

<img width="900" alt="nma_k310-001_m68" src="https://user-images.githubusercontent.com/24490898/220163201-13933a56-1c92-46ac-ae8e-829e21da2130.png">

For testing you may use the [file](https://dme.mozarteum.at/movi/file/311/1) I used (note that the articulation on the chord was added manually).

@frakel

**Comment by wergo** [comment]
@o-sapov Thanks a lot for these comments. Both cases actually do work in the current implementation. You have to `ALT-click` on a note to really select the chord, not the note. Then, both situations work as you suggested. 

The warning screenshot above refers to the selected note that truly does not have and artic attribute.

**Comment by wergo** [comment]
@o-sapov Could you please check the documentation text for this functionality whether it's good to understand: https://mei-friend.github.io/docs/advanced/critapp/

**Comment by o-sapov** [comment]
> @o-sapov Thanks a lot for these comments. Both cases actually do work in the current implementation. You have to `ALT-click` on a note to really select the chord, not the note. Then, both situations work as you suggested.
> 
> The warning screenshot above refers to the selected note that truly does not have and artic attribute.

Yes, this way it works correctly.


> @o-sapov Could you please check the documentation text for this functionality whether it's good to understand: https://mei-friend.github.io/docs/advanced/critapp/

I'll send you en email with my comments on this.
