### ISSUE TITLE
Menu item to turn on/off measure numbers

### ISSUE THREAD

**Issue by Brathenning** [mei-friend/mei-friend#19]
**Problem.**
A lot of pieces don't use measure numbers. Currently you have to navigate to <scoreDef> and add @mnum.visible="false" by hand. Also it would be nice if turning of measures in musescore would translate, but I'm not sure whether the musescore to musicxml export even manages that (quick testing indicates no)

**Potential Solution**
Under the Manipulate tab an option to toogle measure numbers which would add (or change) @mnum.visible to "true" or "false". Maybe even a shortcut.

**Comment by Brathenning** [comment]
Yes the scoreDef@mnum.visible="false" solution works. The idea would be to make that more accessible to people with little expereince of reading documentation by adding this to the manipulate dropdown menu since it is such a common requirement and not entirely easy to find. @musicog asked me to create this issue for that exact reason.

**Comment by Brathenning** [comment]
Wouldn't two items be a lot for such a small change? I think that that would clutter the menue  
how about something like `toggle measure numbers` that acts like a checkbox? It would change `@mnum.visble` to `"false"` if it's `"true"` and the other way around.

**Comment by wergo** [comment]
A toggle would certainly be sufficient. 

How should the exact behavior be: 

1. mei-friend checks the MEI for `scoreDef@mnum.visible` (at every edit operation): 
- If not there, it the menu item says _"Hide measure numbers"_ and adds a `scoreDef@mnum.visible="false"` to all scoreDef elements when clicked. (It seems that Verovio only reacts on the first `scoreDef` element.)
- If there and `"false"`, it says _"Show measure numbers"_ and removes `scoreDef@mnum.visible` from all scoreDef elements (or set them to `"true"`) when clicked.

Alternatively, we could also host this functioniality under the GitHub action menu that @musicog recently added to mei-friend. 

What do you think?

**Comment by Brathenning** [comment]
I don't think using github actions would be better than what you described here. 

The functionality seems sensible but there is the small problem of Verovio only reacting to the first element. I'd argue it'd be best to only check for that first  `scoreDef` for deciding what the toggle button should show. When the user sees measure-numbers, they will have the option to turn them off. Whether or not some other scoreDef element has set `@mnum.visible="false"` shouldn't matter for that. Whether all `scoreDef` elements should be change I can't say. I don't know of situations where you'd have multiple `scoreDef` all containing `mnum.visible`.

**Comment by wergo** [comment]
Fixed through support of GitHub Actions.
