### ISSUE TITLE
Loading on Safari breaks with undefined variable

### ISSUE THREAD

**Issue by ahankinson** [mei-friend/mei-friend#25]
Your issue may already be reported!
Please search on the [issue tracker](https://github.com/mei-friend/mei-friend/issues) before creating a new bug report.

**Error Code**

<img width="1258" alt="image" src="https://github.com/mei-friend/mei-friend/assets/163183/be0edcac-b8ac-4d02-9904-50c3bcf69342">

**Describe the bug**

Lines 838-841 in `main.js` check to see if the browser is Safari. However, this check fails because the variable `lang` is not defined. 

https://github.com/mei-friend/mei-friend/blob/main/app/static/lib/main.js#L838-L841

**To Reproduce**

Load https://mei-friend.mdw.ac.at with Safari.

**Desktop (please complete the following information):**
 - OS: macOS Ventura 13.3
 - Browser Safari
 - Version 16.4

**Comment by wergo** [comment]
Thanks for spotting this! 

Fixed with 40ce65ee8b4839590f87d864089d6bf92d40476d (version 0.9.1) that should go online at 4 July 2023, 11:30 CEST approximately. 

However, after the fix, mei-friend will tell you that Safari is not a good browser for it... ;-)

**Comment by ahankinson** [comment]
Great, it works. Thanks!
