### ISSUE TITLE
Saving locally prevents from using git commits 

### ISSUE THREAD

**Issue by mapscl** [mei-friend/mei-friend#26]
If after a change the MEI-file is saved locally you can not commit the change to a git repository.
That means if you work using github and load your files from there the change can not be saved in the repository anymore after saving the file locally on your device.

You either should be able to always commit if your file is loaded from github or be able to always commit no matter what.

Versions used:
mei-friend staging-0.9.1
Verovio 3.16.0-6dc700d

**Comment by musicog** [comment]
Addressed in v1.2.0 -- with new isomorphic-git integration, ability to commit is now linked to whether git status (internally) reports modifications, independently of whether the MEI has been saved locally.
