### ISSUE TITLE
Error 1649499359728 in Firefox while being logged into GitHub

### ISSUE THREAD

**Issue by annplaksin** [mei-friend/mei-friend#27]
Is someone else able to reproduce this behaviour or is this only happening on my machine?
It would be very kind if someone could try to reproduce this to see if this needs to be fixed.

**Error Code**
1649499359728

**Describe the bug**
While being logged in with GitHub, I receive an error message when clicking this link:
<https://mei-friend.mdw.ac.at/?file=https://raw.githubusercontent.com/EarlyMusicTheory/mei-mensural-skeleton/main/MEI-mensural-skeleton.mei&scale=80&breaks=encoded&speed=false&notationOrientation=top>

It works fine in Chrome and also with Firefox when not being logged in.

**To Reproduce**
1. Use Firefox
2. Log into your GitHub account with mei-friend
3. Click; <https://mei-friend.mdw.ac.at/?file=https://raw.githubusercontent.com/EarlyMusicTheory/mei-mensural-skeleton/main/MEI-mensural-skeleton.mei&scale=80&breaks=encoded&speed=false&notationOrientation=top>
4. See error message
5. Everything works fine after the error message is closed.

**Screenshots**
![grafik](https://github.com/mei-friend/mei-friend/assets/12529090/23ae1a0b-b4d1-446d-a526-0295326b96b4)

**Desktop:**
 - Windows 11
 - Firefox 115.0.2 (64-Bit)

**Comment by wergo** [comment]
@annplaksin Not able to reproduce. It works fine under MacOS 13.4.1 with current Firefox 115, also when logged into GitHub. I will try on a Windows machine.
