### ISSUE TITLE
Fail to load responsibility from file at start and add to markup (e.g. <supplied>)

### ISSUE THREAD

**Issue by annplaksin** [mei-friend/mei-friend#29]
This bug is two-folded:

1. When adding a new person or cooperation with `@xml:id` inside a `<respStmt>` in the header, the list of choices within the settings does not update. Reloading the page is a quick workaround for this one, at least when you're not currently locally debugging something else...
2. If there is a value chosen within the settings menu, e.g. because there is only one valid person with an id in the file, this value is somehow not loaded into `viewer.respId`. When adding markup, like `<supplied>`, `v.respId` is still empty and no responsibility will be added to the markup.

Regarding 1, I don't have a clue how to solve that. Maybe it's not too important because there is a workaround anyway.

Regarding 2, I am currently struggling to understand the mechanics of how settings are added, applied and modified, but as far as I can see:
When loading mei-friend `document.getElementById('respSelect').value` is still empty. But when I look into the settings panel, I see a chosen id:
![grafik](https://github.com/mei-friend/mei-friend/assets/12529090/c246d40e-5fbd-4afc-a895-2d6f33dbf75f)
Using an mei file with two possible responsibilities to choose from, and switching from the first option to the second in the list, it works:
![grafik](https://github.com/mei-friend/mei-friend/assets/12529090/01011517-dcec-4979-b1f9-ca84adf938d6)
 
I am not completely sure, but it seems like the initial attempt of reading the available options into `respSelect` while loading the file into mei-friend seems to fail.

**Comment by wergo** [comment]
Thanks for spotting this. Should be fixed in 95fba08, currently on develop.
