### ISSUE TITLE
Respect key on pitch manipulation 

### ISSUE THREAD

**Issue by rettinghaus** [mei-friend/mei-friend#38]
When moving a note up/down it would be good to take the current key signature into consideration. 

In a piece in G major: 

- moving up diatonically from an _e_ adds an `@acid.ges="s"` to the _f_ `note`
- moving up chromatically from an _e_ adds an `accid` child with `@accid="n"`
- moving down chromatically from an _g_ adds an `@acid.ges="s"` to an _f_ `note` instead of a `g` with accid `f`

**Comment by wergo** [comment]
Thanks a lot for this great suggestion. 

Your examples would behave now like this:
1) Moving up a full tone from `e` will end in `f@accid.ges="s"` 
2) `e` up a semi-tone would end in a `e@accid="s"` (not `f natural`, as you suggested); moving down a semi-tone from `f#` would end in a `f@accid="n"`
3) Moving down a semi-tone from g goes to `f@accid.ges="s"`, as suggested.

It is now implemented with the help of the [base-40 system](https://wiki.ccarh.org/wiki/Base_40) (thanks to CCARH for providing this discussion). (Currently in branch develop-base40, but soon to be merged into staging.)

**Comment by wergo** [comment]
It is now pushed to [https://staging.mei-friend.mdw.ac.at](https://staging.mei-friend.mdw.ac.at). @rettinghaus, could you have a look?

**Comment by rettinghaus** [comment]
Looks great! 🤩  Thank you so much!
