### ISSUE TITLE
Deleting an visual accidental should make it gestural

### ISSUE THREAD

**Issue by rettinghaus** [mei-friend/mei-friend#39]
Deleting an `accid` element should still keep the pitch encoded on `note` as an `@accid.ges`. 

(Then changing the pitch by arrow keys would again make it disappear.)

**Comment by wergo** [comment]
Why do you assume that deleting an `@accid` would imply having an `@accid.ges` there? This might be true, only when key signature or other `@accid` in that measure affects that note. 

The workflow, I had in mind, would be: 
1) Delete the `@accid` (it is deleted) 
2) Run `check @accid.ges` and let it check key signature and measure-wise accidentals
3) Initiate correction function, if appropriate.

You can do 2) and 3) from time to time, no need to do it always after an edit.

**Comment by rettinghaus** [comment]
Thanks. I wasn't aware of the `check @accid.ges` function. But this doesn't turn repeated accidentals into `@accid.ges` attributes. When shifting/transposing a larger groups of notes you end up with repeated accidentals, and I would simply delete the duplicates, expecting that they keep their sounding pitch. 
Selecting following notes and move them up/down again makes the accidentals go away, but there is no natural showing the sounding pitch there, so it makes it a bit hard working fully visual.  

Just to add: this would copy the behavior of "standard" notation programs like Dorico or MuseScore.
