### ISSUE TITLE
User should be alerted to local storage use (GDPR compliance)

### ISSUE THREAD

**Issue by DILewis** [mei-friend/mei-friend#41]
Since there is persistent local storage being used, even if it isn't sent anywhere else, I believe the site is required to inform/receive consent from the user – even if turning that feature off is impossible. 

I'd suggest a simple pop-up the first time the user lands on the editor.

**Comment by wergo** [comment]
Addressed through a splash screen appearing at first application load (merged in [4869c2f](https://github.com/mei-friend/mei-friend/commit/4869c2fdc736861226a0bb2e7e1cb12b2ed8d684)).
