### ISSUE TITLE
Inserting within-measure slur without meter.count / unit causes misleading warning message

### ISSUE THREAD

**Issue by musicog** [mei-friend/mei-friend#49]
**Describe the bug**
When working with an encoding lacking `@meter.count` / `@meter.unit` in `scoreDef` / `staffDef`, or the equivalent  `@count` / `@unit` in `meterSig`, placing a slur between two notes within the same measure currently results in a warning message like:

> Attention with slur (`slur-xml-id`): `note1-xml-id` and `note2-xml-id` are on the same beat position -1

Instead of limiting ourselves to these meter attributes, any valid [`att.meterSigDefault.log`](https://music-encoding.org/guidelines/v5/attribute-classes/att.meterSigDefault.log.html) / [`att.meterSig.log`](https://music-encoding.org/guidelines/v5/attribute-classes/att.meterSig.log.html) attributes should be supported. Particularly, I came across this issue when working with `@meter.sym="common"`. 

**To Reproduce**
1. Go to https://mei-friend.mdw.ac.at?file=https://gist.githubusercontent.com/musicog/e63470e5b6f143829493b5debf11a16c/raw/6b7d1a72429481ab01652edb2224ab08877005c1/gistfile1.txt
2. Select two notes in the same measure
3. Press `s` or `Insert->Slur` to add a slur
4. See warning message (slur is placed correctly)

**Expected behavior**
The warning is misleading in this case and should not be shown. 

**Desktop (please complete the following information):**
 - OS: Fedora Linux
 - Browser: Firefox
 - Version: mei-friend 1.0.0

**Comment by wergo** [comment]
Addressed through [fe65f59](https://github.com/mei-friend/mei-friend/commit/fe65f596d11257e188f7b31b26ba5a9a18591ca2). 

Now, in case of simultaneous time stamps, a slur is not added anymore.
