### ISSUE TITLE
Misleading warning when clicking certain notation elements

### ISSUE THREAD

**Issue by musicog** [mei-friend/mei-friend#52]
Through #10 a warning is displayed when any element without a corresponding xml:id is clicked in the notation. This should be restricted to only show for SVG elements where a straightfoward correspondence to identifiable MEI elements can be established.

**To Reproduce**
1. Open https://mei-friend.mdw.ac.at and the default encoding (Beethoven WoO70)
2. Press Ctrl+M, note that 0 new xml:ids are added (that is, every MEI element that needs one has one already)
3. Click on a note stem (its own <g> element in the SVG, but not an element in the MEI), notice that a warning is now displayed and that it is misleading in this case, since `Manipulate->Add IDs` won't change anything
4. Close the warning, click on the word "TEMA."
5. The warning appears again, and is again misleading since Verovio doesn't persist the ID of the (MEI) `<rend>` into the (SVG) `<tspan>` (maybe this is a Verovio bug?)

**Expected behavior**
The warning message should only appear in cases where following the advice of `Manipulate->Add IDs` would fix the problem. Additionally, we should consider special heuristics, e.g., where clicking on the note stem could scroll to the respective `<note>` in the MEI.

**Version**
mei-friend v1.0.3
Verovio v4.0.1

**Comment by wergo** [comment]
Fixed with 3e64216ded17f1ba199c60237ddf704977f4f218.
