### ISSUE TITLE
Keyboard shortcut to switch modality focus between notation and encoding

### ISSUE THREAD

**Issue by musicog** [mei-friend/mei-friend#55]
**Is your feature request related to a problem? Please describe.**
Although many keyboard shortcuts now work in either the encoding or notation modalities, some are still notation only. For example, when entering a new `<note>` element, I have to either type `stem.dir="up"` or click on the note in the notation and press "x" (after first pressing ctrl+M to assign an xml:id if required) if I want to set the stem direction. For this kind of situation, it would be convenient to have a keyboard shortcut that switches focus from the notation to the encoding and vice versa.

**Describe the solution you'd like**
I would propose a function triggered by a keyboard shortcut (proposal: `ctrl-space`) that:
1. Assigns an XML:ID to the current element if working in the editor panel and one is required;
2. [Switches focus ](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) to the same element in the other modality's panel, where this is possible.

In the example, I could finish typing my new note element (without having to specify xml:id or stem.dir), press the new shortcut to assign an XML:ID and jump to the graphical representation of the new note, and press X to flip the stem direction.

**Comment by wergo** [comment]
Item 2. addressed in db55426b8fecf9d31a323bdadee10377b3e44c70.

Please this and `CMD/CTRL + M` to insert `xml:id`s or use `N` to duplicate the selected note.
