### ISSUE TITLE
Note / rest insertion and conversion

### ISSUE THREAD

**Issue by musicog** [mei-friend/mei-friend#57]
**Is your feature request related to a problem? Please describe.**
It is not currently possible to insert note or rest elements without manually encoding them. This should be possible to do from the notation panel using menu or keyboard shortcuts.

**Describe the solution you'd like**
The following new keyboard shortcuts for the notation panel:

"ctrl-alt-n" => insert new note. This should be created immediately after the currently (last-)selected one, or as the new last note on the currently visible notation fragment (e.g., page). It should copy `@pname`, `@oct`, `@dur` from the nearest predecessor note (or otherwise default to 'c', '4', '4'). 

"r" => convert from a `<note>` to a `<rest>`, and vice versa. Retain `@dur`. Use `@ploc` and `@oloc` to retain `@pname` and `@oct` where available. When converting from rest to note (without `@pname` and/or `@oct`) use the values of the nearest predecessor note or default as above.

**Comment by wergo** [comment]
a) Insert new note (when layer is selected) or duplicate selected chord, note, rest with `N`
b) Convert notes to rests and vice versa with `SHIFT + N`

**Comment by wergo** [comment]
Addressed in a) 7dfaa8c3d09246ed5a16468fbf3dd5295bf93d19 and b) fdc3d42b1e9f56e94e9f13e18744083af89ec0e0
