### ISSUE TITLE
Enhance installation docs

### ISSUE THREAD

**Issue by stefan-balke** [mei-friend/mei-friend#58]
There is some information in the INSTALL.md but they are mentioned nowhere and I found them by chance.

Also: Is it really necessary to have a GitHub App registered for developing the core JS functionalities? Maybe there could be different levels of documentation (running locally, running locally + development, optional: Deploying on your own lab server --> links to other tutorials etc.)

Derived from the JOSS review in https://github.com/openjournals/joss-reviews/issues/6002#issuecomment-1790467282

**Comment by rlskoeser** [comment]
additional comments about installation instructions based on my review for JOSS https://github.com/openjournals/joss-reviews/issues/6002:
- Install instructions should be linked from the readme and probably also from the documentation site; I recommend keeping it as a markdown file in the github repo for ease of findability and maintaining with the code.
- Make it clearer which setup steps are optional and what the impact is of skipping them; e.g., if you don't setup a GitHub app, will things break or will there just be some features that are not available to you?
- Remove the outdated reference about setting the js mimetype (it looks like this has been implemented already in the code).
- For production deploy instructions, I suggest linking to standard Flask deploy instructions and then adding any notes about adjustments or configurations specific to your application.

**Comment by wergo** [comment]
We have extended the descriptions on INSTALL.md and made the registration as GitHub app optional. 

There is a reference to INSTALL.md on README.md and on the documentation pages (Advanced – Developing mei-friend).

**Comment by stefan-balke** [comment]
For me, this issue could be closed. What about you, @rlskoeser?

**Comment by rlskoeser** [comment]
The updates to the instructions look great!

**Comment by wergo** [comment]
Thanks a lot for checking!
