### ISSUE TITLE
Facsimile with non-local images

### ISSUE THREAD

**Issue by rettinghaus** [mei-friend/mei-friend#6]
Not sure if this is a bug or just yet missing functionality, but the facsimile viewer/editor doesn't seem to work with external images: 

```xml
<graphic target="https://api.digitale-sammlungen.de/iiif/image/v2/bsb10527431_00282/full/full/0/default.jpg" />
```

It would be great if this would work too.

**Comment by wergo** [comment]
No, it actually only works with external images. 

Is it a CORS thing of the server? Could you share the MEI file?

**Comment by rettinghaus** [comment]
Here is the file:
[score.xml.zip](https://github.com/Signature-Sound-Vienna/mei-friend-online/files/9929471/score.xml.zip)

I played around with the Beethoven example. It seems to only work if you have defined zones. Is this correct? I would expect the linked files to be shown without any additional information. 

A bit documentation about this feature would be welcome, so what attributes actually are needed and where they are expected.

**Comment by wergo** [comment]
We designed the present functionality around the output from the [Deep Optical Measure Detector](https://measure-detector.edirom.de/) that assumes only `<measure>` to have `@facs` attributes. In your example, you have the facs in `<pb>` and `<staff>` that is why nothing is shown (at the moment). 

How would you show a graphics content if you do not have a facs reference? Based on `@startid` attribute in `<graphic>`?

We are working on documentation; this will be pushed as soon as we have it.

**Comment by wergo** [comment]
The latest staging version of mei-friend (0.6.8 currently available at our staging site https://repo.mdw.ac.at/mei-friend/) supports now `@facs` pointers in `pb` to `surface` elements to be shown. 

For a test file, see [this Beethoven Op.76 file with empty surface elements](https://repo.mdw.ac.at/mei-friend/?notationOrientation=left&notationProportion=.6&facsimileOrientation=left&facsimileProportion=.45&breaks=encoded&file=https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op76_BreitkopfHaertel/master/Beethoven_Op76-Breitkopf-Haertel_pb-facs.mei&page=2). See also #7.

A draft version of a documentation for facsimile is to be found here (please ignore links to other pages for the moment, as the documentation is incomplete): https://mei-friend.github.io/docs/facsimile/
