### ISSUE TITLE
Add developer documentation

### ISSUE THREAD

**Issue by stefan-balke** [mei-friend/mei-friend#60]
The developer documentation is very sparse to non-existing currently :-).
I know, this is much work but will increase the value of the software tremendously. Start with a documentation of the folder structure and the files. Give pointers to the main files and where developers could find a handle. It could also be a short screen-cast showing people how to implement new features.

Derived from the JOSS review in https://github.com/openjournals/joss-reviews/issues/6002#issuecomment-1790467282

**Comment by wergo** [comment]
We have started a page for developers at https://mei-friend.github.io/docs/advanced/structure/ where the main folders and files are described. As requested by #68, we have added a more detailed documentation for contributions to the mei-friend project at https://mei-friend.github.io/docs/advanced/contributing/. 

We will continue explaining the files in app/static/lib in more detail shortly.

**Comment by stefan-balke** [comment]
Yes, this looks good, thanks!
