### ISSUE TITLE
consider making the application installable as a python package

### ISSUE THREAD

**Issue by rlskoeser** [mei-friend/mei-friend#69]
Consider making the application installable as a python package, at least from GitHub even if you don't want to publish it on pypi. You can do this by adding a [pyproject.toml](https://pip.pypa.io/en/stable/reference/build-system/pyproject-toml/) file that describes your package, and includes the python requirements (this replaces requirements.txt). You will need to do configure the package to make sure the necessary non-python static files are included (js/npm dependencies would need to be handled separately).

suggestion from JOSS review https://github.com/openjournals/joss-reviews/issues/6002

**Comment by musicog** [comment]
Thank you for this suggestion. We have improved the build instructions within `INSTALL.md` and streamlined the install process, e.g. to make GitHub configuration optional. The dependencies have been moved into a 'deps' folder and no longer need building; the only remaining npm requirement is for the (newly added) playwright end-to-end tests, as also described in `INSTALL.md`. 

Our expectation is that most users of our application will make use of the hosted version at https://mei-friend.mdw.ac.at. Do you think our newly streamlined installation procedure is sufficiently straight-forward now to cover those users who wish to self-host? Or is a move to a installable python package vastly preferable?
