### ISSUE TITLE
Allow zones to be added graphically

### ISSUE THREAD

**Issue by rettinghaus** [mei-friend/mei-friend#7]
Currently it is only possible to edit zone boxes graphically, but in the facsimile view it is not possible to add a new one. 

A modular system to add facsimiles would be nice: 

* "Add facsimile" would add an empty facsimile tree into the MEI
* "Add graphic" would let you choose an image (and add the element to the surface)
* "Create new zone" would add an empty box (somehow)

**Comment by rettinghaus** [comment]
Every `pb` marks a new page, so if there are `pb` elements in the MEI, a `facsimile` should be created with as many `surface` elements as there are `pb` elements and linked together with `@facs`. 
Then you could add a graphic to each page. 

Compare in TEI: https://www.deutschestextarchiv.de/doku/basisformat/seitenFacsNr.html?hl=facs

This way you could present the facsimiles without the need for individual zones.

**Comment by wergo** [comment]
Thank you for pointing me to this page. I have implemented all requests from above.

This relates to #6.

mei-friend 0.6.8 (currently available at our [staging site](https://repo.mdw.ac.at/mei-friend/)) now supports:
- Inserting blank facsimile elements (Menu bar: `Manipulate -> Insert facsimile element`) with a surface element for each `pb` in the file, pointing to it with a `@facs` attribute. The dummy attribute values for `graphic@target` etc. need to be edited manually.
- Inserting new zones on selected elements (all allowed elements of att.facsimile supported by Verovio). (The functionality of adding a zone and a measure simultaneously was moved to `CMD/CTRL + Click`)

The workflow for inserting zones is: 
1) enable edit mode, 
2) select an element in encoding (such as staff, measure, beam...; it should have an xml:id to work), 
3) click-drag a rectangle in facsimile image. A new zone is added with the `@facs` attribute to the selected element.

Deleting with DELETE key on selected surface; will delete the zone element and the `@facs` attribute of pointing element. 

See [this Beethoven Op.76 file with empty surface elements](https://repo.mdw.ac.at/mei-friend/?notationOrientation=left&notationProportion=.6&facsimileOrientation=left&facsimileProportion=.45&breaks=encoded&file=https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_Op76_BreitkopfHaertel/master/Beethoven_Op76-Breitkopf-Haertel_pb-facs.mei&page=2).

A draft version of a documentation for facsimile is to be found here (please ignore links to other pages for the moment, as the documentation is incomplete): https://mei-friend.github.io/docs/facsimile/
