### ISSUE TITLE
suggestion: revise public repertoire submission template to make it more like a form

### ISSUE THREAD

**Issue by rlskoeser** [mei-friend/mei-friend#71]
Consider revamping your public repertoire submission template so that it looks more like a form with sections, and documentation with each section instead of all at the top. Basically, structure them a bit more like the bug and feature request templates you are using so it is easier for people to fill out the necessary information, and have instructions in place as they do.

suggestion from JOSS review https://github.com/openjournals/joss-reviews/issues/6002

**Comment by wergo** [comment]
Thank you for this suggestion!

Addressed in [aa32123](https://github.com/mei-friend/mei-friend/commit/aa32123970e75c9bd327e7d9b1ca7a93b15d80ad).

**Comment by rlskoeser** [comment]
New version looks great!
