### ISSUE TITLE
UI functionality breaks down if local language is not supported

### ISSUE THREAD

**Issue by axgeertinger** [mei-friend/mei-friend#73]
Javascript execution seems to stop if the local language (Danish, in my case) set for the browser is not supported by mei-friend. User is not displayed as logged in, menu items are irresponsive. Javascript console reports missing language files. See screenshots. Tested in Firefox and Chrome. 
![mei-friend1](https://github.com/mei-friend/mei-friend/assets/3779074/087ceecf-5b5b-4e91-8ffb-2cceea19a1a4)
![mei-friend2](https://github.com/mei-friend/mei-friend/assets/3779074/7a487149-3a68-4ccd-bde8-95bf67236845)

**Comment by wergo** [comment]
Thanks @axgeertinger for raising this! 

Fixed in d5c4f3a9b4657ba2a5023c28fe59b49a823aed34. 

Already pushed to https://mei-friend.mdw.ac.at/ and https://staging.mei-friend.mdw.ac.at/. Should now switch to English when unsupported language code.
