### ISSUE TITLE
Keyboard shortcut renaming measures (SHIFT+R) - probably a bug

### ISSUE THREAD

**Issue by janjusolja** [mei-friend/mei-friend#76]
**Output message**
Renumber measures (Test)

**Describe the bug**
SHIFT + R executes the action, it's not possible to write a capital R anywhere in the code

**Expected behavior**
Being able to type a capital R :)

**Desktop (please complete the following information):**
 - OS: Windows 10 Education
 - Browser: Chrome and Edge
 - Version: 22H2

**Comment by wergo** [comment]
Thanx for spotting this bug!! 

Addressed through 1dc83d3c63bf9d4127d60c31f7f69b0d2d001c0e and pushed to develop, staging, and production site.
