### ISSUE TITLE
Use different keyboard shortcut for annotation panel

### ISSUE THREAD

**Issue by musicog** [mei-friend/mei-friend#88]
As discovered in conversation with @ikyriazi

CTRL-A (select all) is also the keyboard shortcut to open/close the annotation panel. This is somewhat irritating and should be changed!

**Comment by wergo** [comment]
Text fields (Open URL, Solid Login URL) are now accepting default key bindings (301888773a0f99a5ec30eb0d3241cf0aea834523).
