### ISSUE TITLE
"https://schema.org/description" in dataCatalog files

### ISSUE THREAD

**Issue by ikyriazi** [mei-friend/mei-friend#91]
Generated discovery (dataCatalog) json files contain the key-value pair:
`"https://schema.org/description": "Collection of datasets about [dataCatalog file]"`

Wouldn't be more accurate or precise, if we changed the wording to "Collections of datasets `belonging to`, `related to`, or `included in` [dataCatalog file]"?

**Comment by musicog** [comment]
Annotations are generated as with type `schema:Dataset` (as well as `oa:Annotation`) and refer to the corresponding `schema:DataCatalog` via `schema:includedInDataCatalog`.

For the benefit of human readers, the DataCatalog has a `schema:description` reading `Collection of datasets about [annotated (MEI) resource]` -- n.b. not the DataCatalog or the Dataset! 

The DataCatalog also has `schema:about [annotated (MEI) resource]` and `schema:dataset` referring (via a blank node that includes information about the additional oa:Annotation type) to the Dataset / Annotation.

As far as I see this all makes sense -- but if you disagree please feel free to re-open with a comment :-)
