### ISSUE TITLE
MIDI player 'space' key only works when notation in focus

### ISSUE THREAD

**Issue by musicog** [mei-friend/mei-friend#92]
**Describe the bug**
The 'space' key is a keyboard shortcut for starting and stopping MIDI playback, first opening the player if required. It is correctly disabled when focus is on the encoding (otherwise playback would be triggered every time a space is entered into the MEI); but it is also disabled when the focus is not explicitly on the rendered notation. This can be confusing, e.g., when the user has just clicked a menu item somewhere.

**To Reproduce**
1. Open the MIDI player via the menu (View -> Playback controls)
2. Press 'space' key. Player does not play.
3. Click into the rendered notation (e.g., by selecting a note)
4. Press 'space' key. Player starts playing.

**Expected behavior**
Playback should start on 'space' when focus is not currently on encoding panel or other text field (e.g., in settings)

**Comment by wergo** [comment]
Addressed through de493dcc5d45ae0a8b2f7f7e4cf6738ea5487115. 

SPACE key is now connected to `<body>` element with exception to `#encoding`. This will override default behavior, such as in settings panel etc.
