### ISSUE TITLE
Issue with facsimiles in neume notation

### ISSUE THREAD

**Issue by martha-thomae** [mei-friend/mei-friend#93]
There are some issues when showing facsimiles in square neumes.

The facsimile in [CH-E_611_025v_V1-ExampleThatWorks.mei](https://github.com/martha-thomae/chant_in_meifriend/blob/main/CH-E_611_025v_V1-ExampleThatWorks.mei) works when checking the box "Full page". See the following screenshot (where you can see the one zone too as I also checked the "Show zone boxes" option).

![v1 - works](https://github.com/mei-friend/mei-friend/assets/13948831/2d931ef5-d55e-4927-9060-dfc672fd30c1)

However, when I modify the previous file to use another image inside the same repository, it suddenly stops working. See [CH-E_611_025v_V2-OneChangeAndStopsWorking.mei](https://github.com/martha-thomae/chant_in_meifriend/blob/main/CH-E_611_025v_V2-OneChangeAndStopsWorking.mei), here I only changed the `@target` value in `<graphic>`.

![v2 - stops working](https://github.com/mei-friend/mei-friend/assets/13948831/6a0c76b1-26dc-4146-b519-32bd9918598b)

If it makes it easier, you can fork this [repository](https://github.com/martha-thomae/chant_in_meifriend) and check the two files mentioned above in MEI-friend. Thank you so much!

**Comment by wergo** [comment]
@martha-thomae Sorry for the late response. 

This is a bug that will be fixed very soon. However, when operating inside GitHub repos, you could use path names relative to the repository root.

**Comment by wergo** [comment]
The fix (d1a716f4178b08fbad3927d6e3c6ba9513f86ac2) is now pushed to staging. Could you please try out whether it works for you?

https://staging.mei-friend.mdw.ac.at?file=https://raw.githubusercontent.com/martha-thomae/chant_in_meifriend/main/CH-E_611_025v_V2-OneChangeAndStopsWorking.mei

**Comment by martha-thomae** [comment]
Regarding your first comment:

> This is a bug that will be fixed very soon. However, when operating inside GitHub repos, you could use path names relative to the repository root.

You are absolutely right! I could use a relative path and it works! (I thought I did this before and it didn't work, but never mind, all good!)


Second comment:

> The fix ([d1a716f](https://github.com/mei-friend/mei-friend/commit/d1a716f4178b08fbad3927d6e3c6ba9513f86ac2)) is now pushed to staging. Could you please try out whether it works for you?
> 
> https://staging.mei-friend.mdw.ac.at?file=https://raw.githubusercontent.com/martha-thomae/chant_in_meifriend/main/CH-E_611_025v_V2-OneChangeAndStopsWorking.mei

Yes, the fix seems to have worked too :)

I opened the link and I can see now the image and the zone on top. Thank you, Werner!
