### ISSUE TITLE
Issues with facsimile in mensural notation

### ISSUE THREAD

**Issue by martha-thomae** [mei-friend/mei-friend#94]
In mensural notation, voices are distributed over the opening of a book; usually with the soprano and tenor on the left page, and the alto and the bass on the right page of the book opening. Therefore, to encode a mensural piece, one needs at least two pages (the left and right pages of the opening) to contain the full piece. This causes issues for the facsimile shown in the facsimile panel of mei-friend, as one needs to display two pages at once. 

I provide here an example of a mensural piece distributed over the two pages of a book opening (27v and 28r). As can be seen in the two `<graphic>` elements:

- This for the 27v folio (left page of the opening):

    ```xml
    <graphic xml:id="m-0cb6e917-e898-4f85-92d7-0b86a3bb2111" target="https://muret.dlsi.ua.es/images/iiif/2/6:213:masters:27v.jpg/full/full/0/default.jpg"></graphic>
    ```

- This for the 28r folio (right page of the opening):

    ```xml
    <graphic xml:id="m-a0fce9bd-68e0-4655-87a3-0789ffd27a18" target="https://muret.dlsi.ua.es/images/iiif/2/6:213:masters:28r.jpg/full/full/0/default.jpg"></graphic>
    ```

This is the full code: [Missa6.4_Sanctus_Section1_f27v-28r_MENSURAL_SCORE.mei.zip](https://github.com/mei-friend/mei-friend/files/14729420/Missa6.4_Sanctus_Section1_f27v-28r_MENSURAL_SCORE.mei.zip)

The facsimile panel shows only one page, the first one (27r), with the zones corresponding to the systems on that page.

![27v-28r](https://github.com/mei-friend/mei-friend/assets/13948831/ac28e552-3771-41c2-87f3-628bf49b8df0)

-----

If you modify the file so that the second `<graphic>` element has the same page value in `@target` as the first `<graphic>` element (so both having `target="https://muret.dlsi.ua.es/images/iiif/2/6:213:masters:27v.jpg/full/full/0/default.jpg"`), then you will see that the same page is rendered, but now two zones appear per system—those belonging to the ones that are supposed to be on `27v` and those that are supposed to be on `28r`. You can use the following file that includes this modification: 
[Missa6.4_Sanctus_Section1_f27v_twice.mei.zip](https://github.com/mei-friend/mei-friend/files/14729422/Missa6.4_Sanctus_Section1_f27v_twice.mei.zip)

![27v (two systems)](https://github.com/mei-friend/mei-friend/assets/13948831/9a2b8a83-18ec-481c-bdc1-6f3696b0855c)

**Comment by martha-thomae** [comment]
Hi @wergo! Thank you for your answer :)

I would prefer option 2. But indeed, we have an issue when we have lots of images. How difficult would it be to show all the images one after the other (vertically) so that you could scroll through them to see/add/delete zones?

**Comment by wergo** [comment]
@martha-thomae Thanks a lot for your input. 

With version 1.0.13 (479afa7b08f89ea65a61b1e3de9c04b360df1916), mei-friend supports displaying multiple source images at once, based on all elements shown in the notation panel. Thus, if you select `breaks=none` in the notation control bar, all source images are shown side-by-side, each with a title showing the filename of the image.

Could you please test it at https://staging.mei-friend.mdw.ac.at/?

Here a screenshot with the example file your provided: 
<img width="1919" alt="Bildschirmfoto 2024-04-21 um 10 58 19" src="https://github.com/mei-friend/mei-friend/assets/45632600/4f9d7fa6-183c-4d12-a32d-e56cf9e46109">

**Comment by wergo** [comment]
Here an example with `breaks=none` for [Beethoven’s _Andante favori_ WoO57](https://staging.mei-friend.mdw.ac.at/?file=https://raw.githubusercontent.com/trompamusic-encodings/Beethoven_WoO57_BreitkopfHaertel/master/Beethoven_WoO57-Breitkopf.mei&scale=46&breaks=none&select=note-0000001642495417&page=1&speed=true&notationOrientation=left&notationProportion=0.63&facsimileOrientation=bottom&facsimileProportion=0.65) showing all source images at once: 
<img width="1918" alt="Bildschirmfoto 2024-04-21 um 11 01 29" src="https://github.com/mei-friend/mei-friend/assets/45632600/4511f240-6d53-45e9-b6f9-27f82713a108">

**Comment by martha-thomae** [comment]
Thank you so much, @wergo! I am excited to use this now :)
