### ISSUE TITLE
I cannot open files in mei-friend from my github repository

### ISSUE THREAD

**Issue by maxrothman** [mei-friend/mei-friend#95]
### Error Code
None

### Describe the bug
When I try to open a file from a github repository, nothing happens. Afterwards, the UI is left in an intermediate state where the github menu has the chosen file selected, but none of the other UI shows the chosen file.

<video src="https://github.com/mei-friend/mei-friend/assets/2607086/c32364e8-2c6e-4e5b-b8f4-1069be29740e"></video>

I've tested this with a single **private** github repo, and with both mei, uncompressed musicxml, and compressed musicxml files.

### To Reproduce
Preconditions
* Logged into github

Steps to reproduce the behavior: see video above

### Expected behavior
The file is opened in mei-friend

**Desktop:**
 - OS: Mac 12.7.4
 - Browser: Chrome 123.0.6312.59

### Additional context
- In the devtools' network tab, I see 2 failed requests. Both got a 404
  - https://api.github.com/repos/klezmer-archive/digitized-scores/git/blobs/ecaa9fcf4b87c78ca3bed8d5565e834720f6afbe
  - https://api.github.com/repos/klezmer-archive/digitized-scores/contents/mini-corpus/KMDMP%2001-36-945%20%E2%80%94%20Unetanne%20Tokef%20%E2%80%94%20Eric%20Rangell.musicxml
- I see several errors in devtools' console: [mei-friend.mdw.ac.at-1712153795458.log](https://github.com/mei-friend/mei-friend/files/14854481/mei-friend.mdw.ac.at-1712153795458.log)

**Comment by wergo** [comment]
Thanks @maxrothman for reporting this so precisely!

This is an inconsistency of mei-friend's current GitHub integration. 

Is it happening all the time, or does the file open sometimes as expected? (You may try to go back to the repository-level using the back arrow icon in the GitHub menu of mei-friend, and then re-attemting to open the same file again?)

**Comment by maxrothman** [comment]
My pleasure! It happens every time with every file in the repository.

**Comment by maxrothman** [comment]
I've done a little more research into this issue and I think I might've found the source of the problem. The request that fails is `GET https://api.github.com/repos/klezmer-archive/digitized-scores/contents/<path>` and it fails with a `404`. According to the docs for that API:
> ### [Fine-grained access tokens for "Get repository content"](https://docs.github.com/en/rest/repos/contents?apiVersion=2022-11-28#get-repository-content--fine-grained-access-tokens)
>This endpoint works with the following fine-grained token types:
>- [GitHub App user access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-a-user-access-token-for-a-github-app)
>- [GitHub App installation access tokens](https://docs.github.com/en/apps/creating-github-apps/authenticating-with-a-github-app/generating-an-installation-access-token-for-a-github-app)
>- [Fine-grained personal access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token)
>
>The fine-grained token must have the following permission set:
>- "Contents" repository permissions (read)
>
>This endpoint can be used without authentication or the aforementioned permissions if only public resources are requested.

This pretty clearly indicates the cause of the issue: the authentication used on that endpoint isn't working. The (incorrect) auth must be getting ignored on public repos so it works fine, but when it's required for private repos, it doesn't work.

So what's wrong with the auth? This doc offers more clues. It says it works with 3 "fine-grained token types". Of those 3, personal access tokens are clearly not applicable, so that leaves "App installation access tokens" and "User Access Tokens". 
 As far as I can tell, mei-friend is an "OAuth App" not a "Github App", so my guess is that you're using User Access Tokens. I suspect the ultimate issue is that you haven't requested the correct fine-grained permission ("Contents" repository permissions (read)) in your app setup. If that's not it, it might be that you need to [migrate from an Oauth App to a Github App](https://docs.github.com/en/apps/creating-github-apps/about-creating-github-apps/migrating-oauth-apps-to-github-apps).

I'm happy to help in resolving this issue in any way I can, including by contributing a PR, but since the issue appears to be in your Github app registration, I can't really progress further. Please let me know if there's anything else i can do to help resolve this issue! I'm motivated to do so because it's preventing my project from fully rolling out mei-friend.

**Comment by musicog** [comment]
Thanks for the detective work, and sorry for the slowness of response to this issue. 
mei-friend is indeed an 'OAuth' rather than a 'GitHub app', with access to the 'repo' and 'user' scopes. Of these, repo ["grants full access to public and private repositories including read and write access to code, commit statuses, repository invitations, collaborators, deployment statuses, and repository webhooks"](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps)  -- and indeed we make extensive use of private git repositories when working with mei-friend in a number of projects. 

That doesn't of course explain why it doesn't work in your case. I wonder if it might have something to do with the level of access granted to mei-friend by your klezmer-archive github organization? Specifically, could you check whether mei-friend has access granted within [your organization's OAuth application policy settings](https://github.com/organizations/klezmer-archive/settings/oauth_application_policy)?

I'm very keen to help you get this worked out -- if there's nothing obviously wrong on that settings page, perhaps we could organize a Zoom call in the near future to work through this? Please feel free to shoot me a mail at weigl at mdw.ac.at

**Comment by maxrothman** [comment]
Hm, so you have successfully used the github integration with private repos? That does complicate things.

I verified my org's oauth settings (it says approved) and also un- and re-authorized mei-friend from my user's oauth apps, and unfortunately I'm still seeing the same behavior.

One more potential clue: it appears that the API call in question uses basic auth rather than token auth, I wonder if that's something?

I'll take you up on your zoom call offer, thanks so much! Expect an email shortly.

**Comment by maxrothman** [comment]
From our call, we determined that the problem might be the em-dashes in the filename. Here is the filename:

```
KMDMP 03-38-1183 —   — Hannah Ochner (1).mei
```

**Comment by maxrothman** [comment]
I believe I've found the source of the issue: when encoding URLs, mei-friend collapses substrings of multiple spaces into a single space. For example:
```
# Response from https://api.github.com/repos/<org>/<repo>/git/trees/<hash>
# Notice 2 spaces between "a" and "a"
{
  "sha": "31ec66ad297bfaa2fa59b0be888d97b34d67f17f",
  "url": "https://api.github.com/repos/<org>/<repo>/git/trees/31ec66ad297bfaa2fa59b0be888d97b34d67f17f",
  "tree": [
    {
      "path": "a  a.mei",
      "mode": "100644",
      "type": "blob",
      "sha": "cf21cd7578b89d6807d44cc7823e128a3445f46b",
      "size": 38541,
      "url": "https://api.github.com/repos/<org>/<repo>/git/blobs/cf21cd7578b89d6807d44cc7823e128a3445f46b"
    }
  ],
  "truncated": false
}

# Request to https://api.github.com/repos/klezmer-archive/test-private/contents/a%20a.mei
# Notice 1 space (%20) between "a" and "a"
```

The cause appears to be that mei-friend stores the current github file path in the DOM and retrieves it using `.innerText`, and rendered HTML removes multiple repeated spaces. The critical line appears in `github-menu.js:205`:
https://github.com/mei-friend/mei-friend/blob/e9b6f94ff1fa0d3fc584e5148af8d3ec6a22f1fa/app/static/lib/github-menu.js#L204-L207

`loadFile` then uses the argument passed to it to add to the existing file path (L211):
https://github.com/mei-friend/mei-friend/blob/e9b6f94ff1fa0d3fc584e5148af8d3ec6a22f1fa/app/static/lib/github-menu.js#L209-L213

And finally, that `github.filename` is used to issue the request for the file content that eventually results in a 404 (L441):
https://github.com/mei-friend/mei-friend/blob/e9b6f94ff1fa0d3fc584e5148af8d3ec6a22f1fa/app/static/lib/github-menu.js#L436-L442

There's two approaches I see for resolving this issue. First, a quick fix would be to add a whitespace-preserving value for `white-space` in the stylesheet for the path-storing element (either `.branchContents` or `.file`). Such values include `pre`, `pre-wrap`, and `break-spaces`; [they differ in how they handle wrapping of long lines](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space#values). This would cause the rendered DOM to preserve strings of adjacent whitespace, and thus those unaltered filenames would be available via `.innerText`. It might be a good idea to make this change regardless of which approach you choose, since currently mei-friend isn't guaranteed to display the same filename it was given, which could be confusing for users.

A more robust fix might be to have the source of truth for the path be stored somewhere other than the DOM, ideally in some kind of JS object. That would be a more invasive change of course.

Whichever approach you prefer, I'm happy to make a pull request if that would be helpful.

Thank you for your help in resolving this issue!

**Comment by musicog** [comment]
Thanks for identifying the issue -- good sleuthing!

As I mentioned in the call we have plans for an extensive overhall of the git implementation, in part to be able to support other git cloud services beyond GitHub in future. I'll keep your second suggestion, which I agree is a more robust approach, in mind during this work. For now, your CSS solution seems like an appropriate quick fix -- probably with `pre` to preserve trailing spaces (admittedly something of an edge-case).

Would you like to make the change in a PR against the develop branch? (happy to do it for you to, but would be nice to have you listed as a contributor!)

**Comment by musicog** [comment]
Thanks @maxrothman - your fix is now live on our staging environment at https://staging.mei-friend.mdw.ac.at and will be available on the production site after the next release!

**Comment by maxrothman** [comment]
I've verified that the fix on staging resolves my issue. Thank you!

**Comment by maxrothman** [comment]
Just one note: it appears that for long filenames, the filename box pushes the buttons in the top-right off the page. You may want to consider setting that box to `overflow: scroll` or `hidden` or similar.

**Comment by maxrothman** [comment]
I happened to stumble across my [last comment](https://github.com/mei-friend/mei-friend/issues/95#issuecomment-2258420878) here by accident today, @musicog do you want a PR for that?
