### ISSUE TITLE
Theme "solarized dark" not working (is solarized light)

### ISSUE THREAD

**Issue by ohwjd** [mei-friend/mei-friend#97]
When trying to choose the theme "solarized dark" in the dropdown for theme in the mei-friend Editor Settings, the theme is not, as expected dark, but the solarized light version. The solarized light version works as expected, and the other themes also seem like they work as expected.

I encountered the issue in Chrome and Firefox.

**Comment by wergo** [comment]
Thank you @ohwjd for raising this! 

Actually, both solarized versions do not work because the corresponding CSS file has not been copied to the server (the default black colors look like a light theme). Should have been fixed long ago, will be done soon.

**Comment by wergo** [comment]
The missing file has been added to the server. Thanks to Boris Wokurka!
